### ISSUE TITLE
Remove dead code from Grid

### ISSUE THREAD

**Issue by Maikon** [Katerina-codes/battleship_game#5]
[This method](https://github.com/Katerina-codes/battleship_game/blob/master/lib/grid.rb#L12) is only used in tests. Remove it and its corresponding test.

**Comment by Katerina-codes** [comment]
I want to use that for validation, I was using it before then my code changed but now my validation is bad.

**Comment by Maikon** [comment]
Well you currently don't need it. When you do (and it's used) you can put it back again :-)

**Comment by Katerina-codes** [comment]
Done.
